namespace: monobereadlity
name: system
version: 0.1.0
readme: README.md
authors:
description: An Ansible collection to disable automatic suspend and related power saving features.
license:
  - MIT
tags:
  - system
  - fedora
  - suspend
  - gdm
  - gnome
dependencies: {}
repository: https://github.com/monobereadlity/your_repository # Placeholder, will be updated if possible
homepage: https://github.com/monobereadlity/your_repository # Placeholder
issues: https://github.com/monobereadlity/your_repository/issues # Placeholder
