name: Ansible Collection CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Run yamllint
        run: make lint-yaml

      - name: Run ansible-lint
        run: make lint-ansible

  molecule-tests:
    runs-on: ubuntu-latest
    needs: lint # Make it depend on lint job
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule[docker] # molecule[docker] for docker driver support

      - name: Run Molecule tests
        run: make molecule
